### ISSUE TITLE
Cause: non-flavored defaultConfigs must be provided.

### ISSUE THREAD

**Issue by neorix11** [yshrsmz/BuildKonfig#104]
It may be obvious for some but I'm still new to KMM.  I've placed `id("com.codingfeline.buildkonfig") version "0.14.0"` in my `plugins` block and when I'm trying to sync, I get this message: `Cause: non-flavored defaultConfigs must be provided.` 

It doesn't seem I'm even able to import the library.  Any ideas? Thank you.

**Comment by yshrsmz** [comment]
Please refer to the README.
You need to configure the plugin

https://github.com/yshrsmz/BuildKonfig#gradle-configuration

**Comment by ranger163** [comment]
Hi @neorix11 
You need to add the buildKonfig block while you are setting up the library, as it needs defaultConfigs to be there.

buildkonfig {
    packageName = "com.example.app"
    // objectName = "YourAwesomeConfig"
    // exposeObjectWithName = "YourAwesomePublicConfig"

    defaultConfigs {
        buildConfigField(STRING, "name", "value")
    }
}
