### ISSUE TITLE
Add Support to change build types or Build Variants

### ISSUE THREAD

**Issue by shivamkanodia9143** [yshrsmz/BuildKonfig#133]

**Comment by yshrsmz** [comment]
see https://github.com/yshrsmz/BuildKonfig#product-flavor for product flavor support.

see https://github.com/yshrsmz/BuildKonfig/issues/77#issuecomment-1333484782 for Android style build type or variant

**Comment by shivamkanodia9143** [comment]
Hi @yshrsmz sorry for wrong issue, i have already implemented settings build variant from gradle.properties. But i wanted to know is there a way we can change build variant to different type from android studio ui that provides us a way to change build variant as we do in native android, selecting build variant from dropdown, as the issue is for native android we have to change build variant from dropdown but using this BuildKonfig we have to set in grade.properties

**Comment by yshrsmz** [comment]
@shivamkanodia9143 I see.

While I'm not going to implement that functionality, you can achieve almost the same behavior by writing some gradle script. The idea is that changing the `buildkonfig.flavor` property depending on your [gradle starter parameter](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle/-start-parameter/index.html)

see https://github.com/yshrsmz/BuildKonfig/discussions/128 for related discussions.
