### ISSUE TITLE
target ios does not contains correct values. (ComposeApp module hierarchy)

### ISSUE THREAD

**Issue by Moozart** [yshrsmz/BuildKonfig#143]
create("ios") {
            buildConfigField(FieldSpec.Type.STRING, "target", "ios")
        }

But iosX64Main, isoArmX64Main and iosSimulatorArmX64 has  "public actual val target: String = "common""

**Comment by Moozart** [comment]
@RyuNen344  Ofcourse,

kotlin = "1.9.23"
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

**Comment by RyuNen344** [comment]
Yhanks, I'll see later 😉

**Comment by egorikftp** [comment]
@RyuNen344 

I have made investigation, and looks like issue fixes if we specify ios target like this:

```kotlin
targetConfigs {
        create("android") {
            buildConfigField(...)
        }
        create("iosArm64") {
            buildConfigField(...)
        }
        create("iosSimulatorArm64") {
            buildConfigField(...)
        }
        create("iosX64") {
            buildConfigField(...)
        }
    }
```

**Comment by Moozart** [comment]
@egorikftp Araştırma için teşekkürler. Denemedim ama işe yararsa bu scoped func ile kullanacağım. Tek tek tum ios modullerini yazmak beni biraz üşendirdi :)

`fun NamedDomainObjectContainer<TargetConfigDsl>.crateForIOS() {
        listOf("iosArm64", "iosSimulatorArm64", "iosX64").forEach {
            create(it) {
                buildConfigField(FieldSpec.Type.STRING, "target", "ios")
            }
        }
    }
`

**Comment by egorikftp** [comment]
@Moozart 

i can suggest more optimized dsl

```kotlin
fun NamedDomainObjectContainer<TargetConfigDsl>.ios(block: TargetConfigDsl.() -> Unit) {
    listOf("iosArm64", "iosSimulatorArm64", "iosX64").forEach {
        create(it, block)
    }
}

fun NamedDomainObjectContainer<TargetConfigDsl>.android(block: TargetConfigDsl.() -> Unit) {
    create("android", block)
}

fun TargetConfigDsl.buildConfigField(name: String, value: String) {
    buildConfigField(type = STRING, name = name, value = value, const = true)
}
```

Usage

```kotlin

buildkonfig {
    defaultConfigs {
        buildConfigField(name = "versionName", value = "0.0.0")
    }
    
    targetConfigs {
        android {
            buildConfigField(name = "versionName", value = "2.0.0")
        }
        ios {
            buildConfigField(name = "versionName", value = "1.0.0")
        }
    }
}
```
