### ISSUE TITLE
Usage in build.gradle.kts

### ISSUE THREAD

**Issue by clojj** [yshrsmz/BuildKonfig#15]
Hi

How can I do the `buildkonfig` in the Gradle Kotlinscript variant ?

`buildkonfig { }` gives me a syntax error obviously

**Comment by clojj** [comment]
```
plugins {
    kotlin("multiplatform")
    id("kotlinx-serialization")
    id("com.codingfeline.buildkonfig")
}

configure<com.codingfeline.buildkonfig.gradle.BuildKonfigExtension> {
    packageName = "com.example.app"

    // default config is required
    defaultConfigs {
        buildConfigField( com.codingfeline.buildkonfig.compiler.FieldSpec.Type.STRING, "name", "value")
    }
}
```

Problem solved !

**Comment by clojj** [comment]
actually much nicer because of IDE help in the Kotlin DSL

**Comment by clojj** [comment]
works with build.gradle.kts too

**Comment by Murtowski** [comment]
@yshrsmz for Kotlin DSL only syntax mentioned by @clojj works. If this is not fixed, could You please provide in README alternative code snipped for KotlinDSL 🙏🏼

**Comment by yshrsmz** [comment]
As you can see in sample-kts directory, it should work.
