### ISSUE TITLE
Flavor Selection Based on Build Variants in Android

### ISSUE THREAD

**Issue by Egi10** [yshrsmz/BuildKonfig#153]
Currently, the Mobile application (iOS and Android) has build variants (staging, UAT, and prod). At present, to change the flavors, it is done through gradle.properties.

```
// flavor = staging, UAT, or prod
buildkonfig.flavor=prod
```

Is it possible to automatically run the flavor according to the selected build variant in Android without having to change the buildkonfig in gradle.properties?

**Comment by yshrsmz** [comment]
see https://github.com/yshrsmz/BuildKonfig/discussions/128#discussioncomment-7896350

**Comment by Egi10** [comment]
I've tried this, but I always fail here:
 
`val runningTasks = project.gradle.startParameter.taskNames
`
where the result is always emptyList and if I add:

```
gradle.taskGraph.whenReady {
    configureBuildKonfigFlavorFromAndroidTasks()
}
```

the result is: [prepareKotlinIdeaImport, prepareKotlinBuildScriptModel]

Can you please give me a solution for this?

**Comment by yshrsmz** [comment]
Could you comment on the discussion https://github.com/yshrsmz/BuildKonfig/discussions/128 ?
I want to keep all the relevant information/knowledge in one place 🙏

**Comment by Egi10** [comment]
okey, thanks
