### ISSUE TITLE
Add isDebug to generated class

### ISSUE THREAD

**Issue by kuuuurt** [yshrsmz/BuildKonfig#16]
In Android, `BuildConfig` holds a `DEBUG` variable we can use to check the build type.

Can we have this? Would be useful for some cases like enabling Ktor's Logging on debug build but not on release builds.

**Comment by yshrsmz** [comment]
As far as I know, js platform does not have debug/release distinction. That's why BuildKonfig does not offer built-in DEBUG constant. 
But you can manually add by yourself.

**Comment by kuuuurt** [comment]
Do you think it's possible using this technique? https://github.com/ilmat192/kotlin-native-gradle-samples/tree/master/debug-logger

**Comment by yshrsmz** [comment]
Could be, but I haven't tried that configuration.

**Comment by kuuuurt** [comment]
I'll try to submit a PR when I can :)

**Comment by yshrsmz** [comment]
Oh, do you mean to include that in BuildKonfig?
Then I don't want to implement that, sorry. I chose to not implement that kind of workaround to keep it easy to keep up with Kotlin update.

**Comment by kuuuurt** [comment]
Awww. Got it then. :)

**Comment by bartwell** [comment]
Hello @kuuuurt, did you find a solution to implement it for Android and iOS? Could you please provide an example how to implement it?
