### ISSUE TITLE
Issue With New Compiler Options DSL

### ISSUE THREAD

**Issue by iammohdzaki** [yshrsmz/BuildKonfig#160]
I was trying to integrate buildKonfig lib in fresh KMP project from KMP wizard. After Adding all required steps to integrate I started facing error: 
Using **'compilerOptions(KotlinCommonCompilerOptions.() -> Unit): Unit' is an error. Kotlin target level compiler options DSL is not available in this release!**

This is the current Compiler Options DSL in KMP project:
`androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }`

I still made it work by replacing this with older compiler options
` androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "11"
            }
        }
    }`

 - OS: Windows 11
 - BuildKonfig Version  v0.15.1
 - Kotlin Version 2.0.0
 - Gradle Version  8.7

**Comment by AbdelrahmanEsam** [comment]
same

**Comment by valeriyo** [comment]
@iammohdzaki thanks for the workaround!

**Comment by dinesh-thiyagarajan** [comment]
Faced the same issue, is there any proper fix available for this ? other than this workaround ?

**Comment by iammohdzaki** [comment]
@dinesh-thiyagarajan I guess the Kotlin version needs to be updated to 2.0.0 in this library currently it is 1.9.22.
