### ISSUE TITLE
How to support KMM multimodular project?

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [yshrsmz/BuildKonfig#161]
**Describe the bug**
Currently android build is not generating in KMM multi modular project

**To Reproduce**
Create multi modular project and run and try to build release build, it is working, resulting module are not compile 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac Sonoma 14.13.1]
 - BuildKonfig Version [e.g. v0.15.1]
 - Kotlin Version [e.g. v1.9.22]
 - Gradle Version [e.g. v8.3]

**Additional context**

**Comment by yshrsmz** [comment]
Could you fill in the template, and provide a reproducible project?

**Comment by yshrsmz** [comment]
I need more information regarding your project setup, such as a full repro link or a build.gradle/build.gradle.kts which can reproduce your issue.

I'm closing the issue now, but feel free to re-open it with repro.

**Comment by yshrsmz** [comment]
Btw I do have a working KMP multi-module project with the BuildKonfig plugin.
