### ISSUE TITLE
Allow BuildKonfig to be marked with @JsExport

### ISSUE THREAD

**Issue by dellisd** [yshrsmz/BuildKonfig#35]
This is a pretty niche use case, but with Kotlin 1.4's generated TypeScript definitions only top level declarations marked with `@JsExport` will be included.

In my case, I am building a web client in TypeScript (rather than use Kotlin/JS) that makes use of a shared multiplatform module that depends on some API keys that are set through a BuildKonfig object.

Naturally, this would depend on #31.

**Comment by yshrsmz** [comment]
Yes, this should be covered too.

According to [the API document](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/-js-export/), `expect` declaration can not be exported for now.

So `actual` declaration in js sourceset should be annotated, and we need to find a way to check the target platform.

**Comment by yshrsmz** [comment]
So we need to

- annotate the common object with `@JsExport` if there is no target specific BuildKonfig configuration
- or annotate `actual` object in js sourceset
