### ISSUE TITLE
Generate: val -> const val

### ISSUE THREAD

**Issue by Jesus13** [yshrsmz/BuildKonfig#42]
Hi, maybe you can use const for generated config objects? Otherwise, you will not be able to make other constants. Constants will allow you to discard chunks of test code that should not be build for a production code.

![const](https://user-images.githubusercontent.com/7438640/100369681-4762c080-3016-11eb-8fee-44a6ae09808b.png)
```

internal object BuildKonfig {
  val FLAVOR: String = "dev"
}

->

internal object BuildKonfig {
  const val FLAVOR: String = "dev"
}
```

**Comment by yshrsmz** [comment]
If I remember correctly, expect/actual cannot be used with `const`.
It's possible to use `const` when BuildKonfig generates a simple object(when you don't provide target-specific config) but to keep consistency between the 2 cases, I think we should stick to the current implementation

**Comment by yshrsmz** [comment]
I'm going to close this for now.
Feel free to reopen this if you find a way.

**Comment by Prototik** [comment]
@yshrsmz you can expose expect/actual const values with using `@Suppress("CONST_VAL_WITHOUT_INITIALIZER")` on the expect class.
I believe it's a bug in a compiler, and with this suppress i'm using it without any problems since kotlin 1.3.

**Comment by yshrsmz** [comment]
Hi @Prototik, thanks for the great information.

Do you know any source about this?

I found this youtrack issue, but it does not clarify if this is a bug or not
https://youtrack.jetbrains.com/issue/KT-18856/Can-we-have-expectactual-consts

**Comment by Prototik** [comment]
No, I don't have any additional information about this, i discovered it by myself via looking to source code of kotlin compiler. I think this inspection just don't care about expect/actuals and should not be forced on expect declrations (due to fact expect cannot have default implementation of any sort).

I personally used it in my own BuildConfig-like plugin for a couple years already and don't encounter any issues with this suppress, and i think it's generally safe to do that (at least with opt-in behavior as I suggested in #70).

**Comment by Prototik** [comment]
@yshrsmz I found it!
It will be allowed in kotlin 1.7 out-of-box: https://github.com/JetBrains/kotlin/commit/b4c854429fb3f025225b91365fcf5063025a40fa

**Comment by yshrsmz** [comment]
That's great!
Let's move it forward 💪

**Comment by AlexanderEggers** [comment]
@Prototik I just noticed that the latest preview of Kotlin v2 and compose-multiplatform seems to have some issues with @Suppress("CONST_VAL_WITHOUT_INITIALIZER"). It is just a warning but I'm wondering if there is something which can be done to supress that. There are actually quite a lot of these now.

**Comment by Skaldebane** [comment]
Hey there! Is there any progress on this?
Would love to be able to use `const` for the configs.
