### ISSUE TITLE
Build failed when BuildKonfig configuration moved to a separate file 

### ISSUE THREAD

**Issue by ernestkamara** [yshrsmz/BuildKonfig#53]
Hi,

Our `buildkonfig` configuration has grown to 115 lines of code (with formatting), so we extract it to another gradle file.
However, applying this plug-in to our `shared/build.gradle` fails our build with an exception.

## Steps to reproduce:
- Extract `buildkonfig` to a separate gradle file, e.i. `buildkonfig.gradle` in our case.
- Apply the plug-in by add  `apply(from = "$rootDir/gradle/buildkonfig.gradle")` in `shared/build.gradle file`
- Running `./gradlew build` should produce the error below:

## Error:

```bash
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kamara/sandbox/kmm-app/app/shared/build.gradle.kts' line: 133

* What went wrong:
A problem occurred evaluating script.
> No signature of method: buildkonfig_bpv4u8f025ackfhk6ga5bwbu6.buildkonfig() is applicable for argument types: (buildkonfig_bpv4u8f025ackfhk6ga5bwbu6$_run_closure1) values: [buildkonfig_bpv4u8f025ackfhk6ga5bwbu6$_run_closure1@5dd086a8]
```

**Comment by yshrsmz** [comment]
I think it's an issue with Gradle configuration.

Could you try extract other plugin's config block to a file, just like you did with buildkonfig, and see how it goes?

**Comment by yshrsmz** [comment]
Closing for now.
Feel free to re-open the issue when you have further information.
