### ISSUE TITLE
Kotlin v1.5.31, XCFramework: targetConfigs fields not found from iOS

### ISSUE THREAD

**Issue by eirikvaa** [yshrsmz/BuildKonfig#59]
First of all, thanks so much for an awesome library!

I have a KMM project that was upgraded to Kotlin v1.5.31 recently. With that release came support for generating an XCFramework that can be consumed from the iOS app, which is awesome since it lets you bundle up different app variants like one for the simulator and one for physical devices.

Previously I would use BuildKonfig and its `targetConfigs` option to create fields for different platforms, `ios` among them. This worked fine on Kotlin v1.5.10. After upgrading to v1.5.31, the fields in the `defaultConfigs` are found, but not the ones in `targetConfigs`.

- Kotlin: 1.5.31
- Gradle: 7.0.2
- BuildKonfig: 0.10.2

**Comment by eirikvaa** [comment]
I'll see if I can create a reproducible project tomorrow.

**Comment by yshrsmz** [comment]
I'm going to look into this tomorrow(or next weekend), but at first glance it must be related to #38 .

For now BuildKonfig cannot detect which is non-root shared sourceset.

This is something I really want to support. Any suggestion (and of course repro) is appreciated.

**Comment by eirikvaa** [comment]
Thanks for coming back to me so quickly, appreciate it :) I'll see about that repro when I have time.

**Comment by yshrsmz** [comment]
Hi, I've released v0.11.0 with (experimental) HMPP support.
Please let me know if you find anything strange.

**Comment by eirikvaa** [comment]
Awesome work, thank you! I tested it a bit last week and it seems to work great :-)
