### ISSUE TITLE
Generating Non-Internal BuildKonfig object

### ISSUE THREAD

**Issue by mustafaozhan** [yshrsmz/BuildKonfig#74]
Currently, if we need to use BuildKonfig from different module, it is not visible since `BuildKonfig` is generated internal, maybe we can make this optional, since it causes repeated setups in different modules

**Comment by yshrsmz** [comment]
You can use `exposeObjectWithName` to make it public

**Comment by mustafaozhan** [comment]
It works! thanks a lot!
