### ISSUE TITLE
can support kotlin Native ?

### ISSUE THREAD

**Issue by CMingTseng** [yshrsmz/BuildKonfig#76]
Dear Sir

as this project  - https://github.com/bennyhuo/hello-kni

can use kotlin native to JNI  ( kotlin  --> c --> JNI --->Android/JVM)

when call  JNI  System.loadLibrary  is  "knlib"  , that define  at sharedLib  in build.gradle.kts 

https://github.com/bennyhuo/hello-kni/blob/27f787c13c27a2fd2e922b632eee66676761fce6/nativeLib/build.gradle.kts#L17

if use  BuildKonfig to define a String buildConfigField like "JNI_NAME_PREFIX" value is "knlib"

we will get buildConfigField at app 

but it can not work 

THX

**Comment by yshrsmz** [comment]
Hi
BuildKonfig supports K/N.

If what you mean is "how to access BuildKonfig defined in 'shared' module, from 'app' module", then BuildKonfig has `internal` visibility modifier by default, so use `exposeObjectWithName` to make it public.

**Comment by CMingTseng** [comment]
> 
Dear Sir

sorry for  my pool kotlin skill

hava any simple demo ?

THX

**Comment by yshrsmz** [comment]
https://github.com/yshrsmz/BuildKonfig#try-out-the-sample

You can modify `sample` project to try out various combinations.

**Comment by CMingTseng** [comment]
> https://github.com/yshrsmz/BuildKonfig#try-out-the-sample
> 
> You can modify `sample` project to try out various combinations(see `sample/build` directory to check what is generated).

Dear  Sir

as  your   sample 

        buildConfigField(FieldSpec.Type.STRING, "test", "testvalue")
        
        https://github.com/yshrsmz/BuildKonfig/blob/3618fb98e5ff6b65269057324e578243d631bbfe/sample-kts/build.gradle.kts#L78
        
        when i want use  "test"  at kt file
        
        how to do ?
        
        at android when set 

  buildConfigField(
            "String",
            "test",
            "\"testvalue\""
        )
        
        we can use it by  xxx.xxx.xxx.BuildConfig.test
        
        THX

**Comment by yshrsmz** [comment]
if you look at `build` directory, you'll find `buildkonfig` directory and that directory includes generated objects for all targets.

You can just import and use it just like ordinary object
