### ISSUE TITLE
Readme does not document hierarchical project support

### ISSUE THREAD

**Issue by dalewking** [yshrsmz/BuildKonfig#79]
Ran into issue now that we have switched to KMM hierarchical project support and I see in the change log that you supposedly support it. However the readme was never updated explaining how to do it and in fact it says that it is not supported.

**Comment by yshrsmz** [comment]
True.
Would you like to send a PR?

**Comment by yshrsmz** [comment]
Sorry I did add the section about HMPP

https://github.com/yshrsmz/BuildKonfig#hmpp-support

but can be improved
