### ISSUE TITLE
Type ...BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by Nailik** [yshrsmz/BuildKonfig#80]
When using Multiple KMM Modules in one Project like

- shared-ui
- shared-logic
- shared-ressources

And one of those modules use `BuildKonfig` then there is a `build\generated\resource\buildConfig\debug\packagename\BuilConfig.kt` file foreach Module which results in `:androidApp:mergeLibDexDebug FAILED`

**Comment by yshrsmz** [comment]
@Nailik Which Kotlin version are you using?
Also, simple repro is greatly appreciated

**Comment by Nailik** [comment]
@yshrsmz Sorry this issue is WRONG i accidentially have setup the same namespace for each android module

```
android {
    namespace = ...
}
```

Therefore i had multiple android `BuildConfig.kt` files, but it has nothing to do with `BuildKonfig`
