### ISSUE TITLE
BuildKonfig doesn't work with npm-publish

### ISSUE THREAD

**Issue by Tihon-Ustinov** [yshrsmz/BuildKonfig#81]
Empty project can't download dependencies when I use id("com.codingfeline.buildkonfig") version "0.13.3" with id("dev.petuska.npm.publish") version "3.2.1"

Steps to reproduce.

Just create multiplatform project and add dependencies like this.

```gradle
plugins {
    kotlin("multiplatform") version "1.6.21"
    id("com.codingfeline.buildkonfig") version "0.13.3"
    id("dev.petuska.npm.publish") version "3.2.1"
}

group = "me.tihus"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

val ktorVersion = "2.1.2"
kotlin {
    js(IR) {
        binaries.library()
        browser()
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
            }
        }
        val commonTest by getting
        val jsMain by getting
        val jsTest by getting
    }
}

```

And you'll get the error 
![image](https://user-images.githubusercontent.com/15249713/222378579-1e110d13-d130-4fd4-955f-90db4c93c379.png)

**Comment by yshrsmz** [comment]
As stated in the error message, you need to define `non-flavored defaultConfigs`

**Comment by yshrsmz** [comment]
Or if it's a root project and you actually want to use BuildKonfig in a child module, then you should add `apply false` in the root `build.gradle`

```
plugins {
  kotlin("multiplatform") version "1.6.21"
  id("com.codingfeline.buildkonfig") version "0.13.3" apply false
  id("dev.petuska.npm.publish") version "3.2.1"
}
```

**Comment by Tihon-Ustinov** [comment]
> 

Ok, Would you help me with that? How can I define it?

**Comment by yshrsmz** [comment]
we covered it in README
please follow the instruction

https://github.com/yshrsmz/BuildKonfig#gradle-configuration
