### ISSUE TITLE
non-flavored defaultConfigs must be provided.

### ISSUE THREAD

**Issue by youranshul** [yshrsmz/BuildKonfig#85]
Hi, I have used your library in my project for making use of product flavor and build configs but I am getting this below issue while integrating with it. You can reproduce issue in my repo :https://github.com/youranshul/KmmMovieBuff

`* What went wrong:
A problem occurred configuring project ':shared'.
> non-flavored defaultConfigs must be provided.`

**Comment by yshrsmz** [comment]
This is because you applied the buildkonfig plugin, but doesn't configure it with `buildkonfig` block

**Comment by youranshul** [comment]
@yshrsmz  how to configure it with block? while applying buildkonfig plugin itself it is throwing the error. Am I missing something?

**Comment by yshrsmz** [comment]
@youranshul Please follow the instruction in README
