### ISSUE TITLE
Rename `buildkonfig` to `buildKonfig`

### ISSUE THREAD

**Issue by hanssonduck** [yshrsmz/BuildKonfig#87]
Hello, great project.
First of all feel free to close this if it's out of scope.

In my opinon the `buildkonfig` DSL option should be renamed to `buildKonfig` so it aligns with the Android counterpart. It's a breaking change but maybe the plugin can accept both versions under a migration period?

**Comment by yshrsmz** [comment]
Hi, thanks for your suggestion.

The name aligns with the plugin name.
You write `apply plugin: 'com.codingfeline.buildkonfig'`, and you use the same `buildkonfig` for the extension name. I think it's easy to understand.

Technically, there is no counterpart for top-level `buildkonfig` extension in AGP. If you are talking about `buildConfigField`, BuildKonfig provides the same API name for that.
