### ISSUE TITLE
Support for Kotlin 1.9.0?

### ISSUE THREAD

**Issue by sakalaus** [yshrsmz/BuildKonfig#88]
Hi.

Apparently the latest BuildKonfig version 0.13.3 is not compatible with Kotlin 1.9.0 and newer.

**Comment by yshrsmz** [comment]
Would you like to contribute?

Also, repro is greatly appreciated.

**Comment by sakalaus** [comment]
Here are some problems I have encountered:

"Android" function has been renamed to "Android target".
[https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#rename-of-android-target-to-androidtarget](url)

Also, there's a new concept of Default hierarchy [https://kotlinlang.org/docs/multiplatform-hierarchy.html#default-hierarchy](url). If you try to use it in the build.gradle, you will get "Unresolved reference: targetHierarchy".

**Comment by yshrsmz** [comment]
should be resolved with v0.14.0
https://github.com/yshrsmz/BuildKonfig/releases/tag/v0.14.0

**Comment by sakalaus** [comment]
v0.14.0 works fine. Thank you!
