### ISSUE TITLE
 SourceSet change support

### ISSUE THREAD

**Issue by vkwofm1** [yshrsmz/BuildKonfig#98]
Please support the change so that a custom sourceSet other than commonMain can be used.

**Comment by yshrsmz** [comment]
@vkwofm1 What do you mean by "custom SourceSet"?
How do you want to configure your source sets and BuildKonfig?

**Comment by vkwofm1** [comment]
My project is designed with a clean architecture structure.
An issue was opened to configure the app module and presentation module of the android project.

It seems to be the same issue as the one below.
https://github.com/yshrsmz/BuildKonfig/issues/77

![스크린샷 2023-08-23 오전 11 04 46](https://github.com/yshrsmz/BuildKonfig/assets/61372446/a9ece0cc-79a7-4e6b-96c8-e724141da298)

**Comment by yshrsmz** [comment]
@vkwofm1 How do you configure dependencies between these source sets? Can you share related sections of `build.gradle`?

If you are talking about intermediate source sets, BuildKonfig does support it

https://github.com/yshrsmz/BuildKonfig#hmpp

**Comment by vkwofm1** [comment]
![스크린샷 2023-08-24 오후 4 01 46](https://github.com/yshrsmz/BuildKonfig/assets/61372446/4a607e79-e48d-4fba-b8cb-ed6e51eeb1da)

**Comment by yshrsmz** [comment]
Thanks, that looks like an intermediate source sets and is different from #77

Please refer to README.
https://github.com/yshrsmz/BuildKonfig#hmpp

**Comment by yshrsmz** [comment]
@vkwofm1 By the way, if you want BuildKonfig for each layer without limitation, you can achieve that by creating module by layer.
